project/models.py
from project import db,bcrypt
from flask_login import UserMixin


class User(db.Model, UserMixin):
  __tablename__ = "users"

  id = db.Column(db.Integer, primary_key=True)
  email = db.Column(db.Text, unique=True)
  password = db.Column(db.Text)
  firstname = db.Column(db.Text)
  lastname = db.Column(db.Text)


  def __init__(self, email, password, firstname, lastname):
    self.email = email
    self.password = bcrypt.generate_password_hash(password).decode('UTF-8')
    self.firstname = firstname
    self.lastname = lastname

  @classmethod
  def authenticate(cls, email, password):
    found_user = cls.query.filter_by(email = email).first()
    if found_user:
        authenticated_user = bcrypt.check_password_hash(found_user.password, password)
        if authenticated_user:
            return found_user
    return False

    def __repr__(self):
      return "Username {} Password hidden".format(self.email)


class Description(db.Model):
  __tablename__ = "descriptions"

  id = db.Column(db.Integer, primary_key=True)
  name  = db.Column(db.Text)
  description = db.Column(db.Text)
  skus = db.relationship('Sku', backref='description', lazy='dynamic', cascade='delete')

  def __init__(self, name, description):
    self.name = name
    self.description = description

  def __repr__(self):
    return "The description is ' {} ' ".format(self.description)

class Sku(db.Model):
  __tablename__ = "skus"

  id = db.Column(db.Integer, primary_key=True)
  sku = db.Column(db.Text)
  description_id = db.Column(db.Integer, db.ForeignKey('descriptions.id'))
  size = db.Column(db.Text)
  color = db.Column(db.Text)
  img = db.Column(db.Text)
  inventories = db.relationship('Inventory', backref='sku', lazy='dynamic')
  transactions = db.relationship('Transaction', backref='sku', lazy='dynamic')

  def __init__(self, sku, description_id, size, color, img):
    self.sku = sku
    self.description_id = description_id
    self.size = size
    self.color = color
    self.img = img


  def __repr__(self):
    return "The sku is ' {} ', descr id is {}, size {}, color {}, img {}".format(self.sku, self.description_id, self.size, self.color, self.img)

class Transaction(db.Model):
  __tablename__ = "transactions"

  id = db.Column(db.Integer, primary_key=True)
  sku_id = db.Column(db.Integer, db.ForeignKey('skus.id'))
  date = db.Column(db.DateTime)
  qty = db.Column(db.Integer)
  type  = db.Column(db.Text)
  description = db.Column(db.Text)
  amount = db.Column(db.Float)
  shipping_cost = db.Column(db.Float)
  shipping_method = db.Column(db.Text)


  def __init__(self, sku_id, date, qty, type, description, amount, shipping_cost, shipping_method):
    self.sku_id = sku_id
    self.date = date
    self.qty = qty
    self.type = type
    self.description = description
    self.amount = amount
    self.shipping_cost = shipping_cost
    self.shipping_method = shipping_method

  def __repr__(self):
    return "sku_id {}, date {}, qty {}, type {}, desc {}, amount {} shipping cost {} shipping method {}".format(self.sku_id, self.date, self.qty, self.type, self.description, self.amount, self.shipping_cost, self.shipping_method)

class Inventory(db.Model):
  __tablename__ = "inventories"

  id = db.Column(db.Integer, primary_key=True)
  sku_id = db.Column(db.Integer, db.ForeignKey('skus.id'))
  amount = db.Column(db.Float)
  date = db.Column(db.DateTime)
  qty = db.Column(db.Integer)

  def __init__(self, sku_id, date, amount, qty):
    self.sku_id = sku_id
    self.date = date
    self.amount = amount
    self.qty = qty

  def __repr__(self):
    return "The sku id ' {} ', date {}, amount {}, qty {}".format(self.sku_id, self.date, self.amount, self.qty)

project/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, validators, PasswordField
from wtforms.validators import DataRequired

class UserForm(FlaskForm):
  email = StringField('E-mail', [validators.Email()])
  password = PasswordField('Password', validators=[DataRequired()])
  firstname = StringField('First Name', [validators.Length(min=1)])
  lastname = StringField('Last Name', [validators.Length(min=1)])


class UserLogin(FlaskForm):
  email = StringField('E-mail', [validators.Length(min=3)])
  password = PasswordField('Password', validators=[DataRequired()])

project/__init__.py
from flask import Flask, redirect, url_for, render_template
from flask_sqlalchemy import SQLAlchemy
from flask_modus import Modus
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_login import current_user
import os

app = Flask(__name__)
app.config['SECRET_KEY'] = os.environ.get('SECRET_KEY')
app.config['SQLALCHEMY_DATABASE_URI'] = 'postgres://localhost/warehouse_sales'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

bcrypt = Bcrypt(app)
modus = Modus(app)
db = SQLAlchemy(app)

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'users.login'
login_manager.login_message = ''


from project.models import User

@login_manager.user_loader
def load_user(user_id):
  return User.query.get(user_id)


from project.users.views import users_blueprint
app.register_blueprint(users_blueprint, url_prefix='/users')

from project.descriptions.views import descriptions_blueprint
app.register_blueprint(descriptions_blueprint, url_prefix='/descriptions')

from project.skus.views import skus_blueprint
app.register_blueprint(skus_blueprint, url_prefix='/descriptions/<int:description_id>/skus')

from project.transactions.views import transactions_blueprint
app.register_blueprint(transactions_blueprint, url_prefix='/descriptions/<int:description_id>/skus/<int:sku_id>/transactions')

from project.transactions.views import transactions_blueprint
app.register_blueprint(transactions_blueprint, url_prefix='/transactions/pick')


from project.inventories.views import inventories_blueprint
app.register_blueprint(inventories_blueprint, url_prefix='/<int:sku_id>/inventories')

@app.route('/')
def root():
  if(current_user.is_authenticated):
      return render_template('users/index.html')
  return redirect(url_for('users.index'))


from project.models import Transaction
@app.route('/orders')
def orders():
  if(current_user.is_authenticated):
    orders = Transaction.query.all()
    return render_template('transactions/order.html', orders = orders)
  return redirect(url_for('users.login'))

@app.route('/sales')
def sales():
  if(current_user.is_authenticated):
    orders = Transaction.query.all()
    return render_template('transactions/sale.html', orders = orders)
  return redirect(url_for('users.login'))

project/descriptions/views.py
from flask import render_template, Blueprint
from project.models import Description
from flask_login import login_required

descriptions_blueprint = Blueprint(
    'descriptions',
    __name__,
    template_folder='templates'
)

@descriptions_blueprint.route('/')
# @login_required
def index():
  return render_template('descriptions/index.html', descriptions = Description.query.all())

@descriptions_blueprint.route('/new')
# @login_required
def new():
  return render_template('descriptions/new.html')

project/inventories/views.py
from flask import render_template, Blueprint
from flask_login import login_required

inventories_blueprint = Blueprint(
    'inventories',
    __name__,
    template_folder='templates'
)

@inventories_blueprint.route('/')
@login_required
def index():
  return render_template('inventories/index.html')

@inventories_blueprint.route('/new')
@login_required
def new():
  return render_template('inventories/new.html')

project/skus/views.py
from flask import render_template, Blueprint

skus_blueprint = Blueprint(
  'skus',
  __name__,
  template_folder='templates'
)

@skus_blueprint.route('/')
def index(description_id):
  return render_template('skus/index.html')

@skus_blueprint.route('/new')
def new():
  return render_template('skus/new.html')


@skus_blueprint.route('/<int:id>/edit')
def edit(id):
  return render_template('skus/edit.html')

project/transactions/views.py
from flask import render_template, Blueprint
from flask_login import login_required

# import datetime
# datetime.datetime.now()

transactions_blueprint = Blueprint(
    'transactions',
    __name__,
    template_folder='templates'
)

@transactions_blueprint.route('/')
# @login_required
def index(description_id, sku_id):
  return render_template('transactions/index.html')

@transactions_blueprint.route('/new')
# @login_required
def new():
  return render_template('transactions/new.html')

project/users/views.py
from flask import redirect, render_template, request, url_for,Blueprint, flash
from project.models import User
from project.users.forms import UserForm, UserLogin
from functools import wraps
from flask_login import login_user, logout_user, current_user, login_required
from project import db, bcrypt

from sqlalchemy.exc import IntegrityError

users_blueprint = Blueprint(
    'users',
    __name__,
    template_folder='templates'
)

def ensure_correct_user(fn):
  @wraps(fn)
  def wrapper(*args, **kwargs):
    if kwargs.get('id') != current_user.id:
      flash('Not Authorized')
      return redirect(url_for('users.index'))
    return fn(*args, **kwargs)
  return wrapper


@users_blueprint.route('/signup', methods=['GET', 'POST'])
def signup():
  form = UserForm(request.form)
  if request.method == 'POST' and form.validate_on_submit():
      flash("You have succesfully signed up!")
      try:
        new_user = User(
          form.data['email'], \
          form.data['password'],\
          form.data['firstname'],\
          form.data['lastname'],
          )
        db.session.add(new_user)
        db.session.commit()
      except IntegrityError as e:
        flash("E-mail already taken")
        return render_template('signup.html', form=form)
      return redirect(url_for('users.index'))
  return render_template('users/signup.html', form=form)

@users_blueprint.route('/login', methods = ['GET', 'POST'])
def login():
  form = UserLogin(request.form)
  if request.method == 'POST':
    if form.validate():
      user = User.authenticate(form.data['email'], form.data['password'])
      if user:
        login_user(user)
        flash("Welcome!")
        return redirect(url_for('users.show', id=user.id))
      else:
        flash("Invalid Credentials")
    else:
      return render_template('users/login.html', form=form, animation='fadein')
  return render_template('users/login.html', form=form, animation='login')

@users_blueprint.route('/logout')
@login_required
def logout():
  # flash('You have been signed out.')
  logout_user()
  return redirect(url_for('users.index'))


@users_blueprint.route('/')
@login_required
def index():
  return render_template('users/index.html', users=User.query.all())

@users_blueprint.route('/<int:id>/edit')
@login_required
@ensure_correct_user
def edit(id):
  found_user = User.query.get_or_404(id)
  form = UserForm(obj=found_user)
  return render_template('users/edit.html', user=found_user, form=form)

@users_blueprint.route('/<int:id>', methods=['GET', 'PATCH', 'DELETE'])
# @login_required
# @ensure_correct_user
def show(id):
  found_user = User.query.get_or_404(id)
  if request.method == b"PATCH":
    form = UserForm(request.form)
    if form.validate():
      flash("Update Successful")
      found_user.email = form.data['email']
      found_user.password = bcrypt.generate_password_hash(form.data['password']).decode('UTF-8')
      found_user.firstname = form.data['firstname']
      found_user.lastname = form.data['lastname']
      db.session.add(found_user)
      db.session.commit()
      return redirect(url_for('users.index'))
    return render_template('users/edit.html', users=found_user, form=form)
  if request.method == b"DELETE":
    flash("User Deleted")
    db.session.delete(found_user)
    db.session.commit()
    logout_user()
    return redirect(url_for('users.index'))
  return render_template('users/show.html', users=found_user)

project/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% block head %}
    <title>{% block title %}{% endblock %}</title>
    {% endblock %}
    <!-- Bootstrap CSS -->


  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/lib/bootstrap-3.3.7-dist/css/bootstrap.min.css') }}">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="{{ url_for('static', filename='css/lib/bootstrap-3.3.7-dist/js/bootstrap.min.js') }}"></script>

    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/style.css') }}">


  </head>
  <body>



    <nav class="navbar  navbar-default navbar-fixed-top light-blue">
      <!--<nav class="navbar navbar-inverse"> BGCOLOR CHANGE TO BLACK-->
      <!--<div class="container-fluid">  ALIGN LEFT-->
       <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false" >
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
         <!--  <a class="navbar-brand" href="#">Sales Revenue</a> -->
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li>
              <a class="nav-link" href="{{url_for('root')}}">Home</a>
            </li>
            <li>
              <a class="nav-link" href="{{url_for('orders')}}">Pick Items</a>
            </li>
            <li>
             <a class="nav-link" href="{{url_for('sales')}}">Sales </a>
            </li>
            <li>
             <a class="nav-link" href="#">Upload</a>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
              {% if current_user.is_authenticated %}
                <a class="nav-link" href="{{url_for('users.logout')}}"> Logout </a>
              {% else %}
                <a class="nav-link" href="{{url_for('users.login')}}"> Login</a>
              {% endif %}
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <br>
    <br>
    <br>


    <div class="container">
       {% with messages = get_flashed_messages() %}
        {% if messages %}
          {% for message in messages %}
            <p>{{ message }}</p>
          {% endfor %}
        {% endif %}
      {% endwith %}
    </div>

    {% block content %}
    {% endblock %}
   <br>
    <br>
    <br>
    <br>
    <br>   <br>
    <br>
    <br>
    <br>
    <br>   <br>
    <br>
    <br>
    <br>
    <br>   <br>
    <br>
    <br>
    <br>
    <br>   <br>
    <br>
    <br>
    <br>
    <br>   <br>
    <br>
    <br>
    <br>
    <br>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
  </body>
</html>