project/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, validators, PasswordField
from wtforms.validators import DataRequired

class UserForm(FlaskForm):
  email = StringField('E-mail', [validators.Email()])
  password = PasswordField('Password', validators=[DataRequired()])
  firstname = StringField('First Name', [validators.Length(min=1)])
  lastname = StringField('Last Name', [validators.Length(min=1)])


class UserLogin(FlaskForm):
  email = StringField('E-mail', [validators.Length(min=3)])
  password = PasswordField('Password', validators=[DataRequired()])

project/users/views.py
from flask import redirect, render_template, request, url_for,Blueprint, flash
from project.models import User
from project.users.forms import UserForm, UserLogin
from functools import wraps
from flask_login import login_user, logout_user, current_user, login_required
from project import db, bcrypt

from sqlalchemy.exc import IntegrityError

users_blueprint = Blueprint(
    'users',
    __name__,
    template_folder='templates'
)

def ensure_correct_user(fn):
  @wraps(fn)
  def wrapper(*args, **kwargs):
    if kwargs.get('id') != current_user.id:
      flash('Not Authorized')
      return redirect(url_for('users.index'))
    return fn(*args, **kwargs)
  return wrapper


@users_blueprint.route('/signup', methods=['GET', 'POST'])
def signup():
  form = UserForm(request.form)
  if request.method == 'POST' and form.validate_on_submit():
      flash("You have succesfully signed up!")
      try:
        new_user = User(
          form.data['email'], \
          form.data['password'],\
          form.data['firstname'],\
          form.data['lastname'],
          )
        db.session.add(new_user)
        db.session.commit()
      except IntegrityError as e:
        flash("E-mail already taken")
        return render_template('signup.html', form=form)
      return redirect(url_for('users.index'))
  return render_template('users/signup.html', form=form)

@users_blueprint.route('/login', methods = ['GET', 'POST'])
def login():
  form = UserLogin(request.form)
  if request.method == 'POST':
    if form.validate():
      user = User.authenticate(form.data['email'], form.data['password'])
      if user:
        login_user(user)
        flash("Welcome!")
        return redirect(url_for('users.show', id=user.id))
      else:
        flash("Invalid Credentials")
    else:
      return render_template('users/login.html', form=form, animation='fadein')
  return render_template('users/login.html', form=form, animation='login')

@users_blueprint.route('/logout')
@login_required
def logout():
  # flash('You have been signed out.')
  logout_user()
  return redirect(url_for('users.index'))


@users_blueprint.route('/')
@login_required
def index():
  return render_template('users/index.html', users=User.query.all())

@users_blueprint.route('/<int:id>/edit')
@login_required
@ensure_correct_user
def edit(id):
  found_user = User.query.get_or_404(id)
  form = UserForm(obj=found_user)
  return render_template('users/edit.html', user=found_user, form=form)

@users_blueprint.route('/<int:id>', methods=['GET', 'PATCH', 'DELETE'])
# @login_required
# @ensure_correct_user
def show(id):
  found_user = User.query.get_or_404(id)
  if request.method == b"PATCH":
    form = UserForm(request.form)
    if form.validate():
      flash("Update Successful")
      found_user.email = form.data['email']
      found_user.password = bcrypt.generate_password_hash(form.data['password']).decode('UTF-8')
      found_user.firstname = form.data['firstname']
      found_user.lastname = form.data['lastname']
      db.session.add(found_user)
      db.session.commit()
      return redirect(url_for('users.index'))
    return render_template('users/edit.html', users=found_user, form=form)
  if request.method == b"DELETE":
    flash("User Deleted")
    db.session.delete(found_user)
    db.session.commit()
    logout_user()
    return redirect(url_for('users.index'))
  return render_template('users/show.html', users=found_user)

project/users/templates/users/edit.html
{% extends 'base.html' %}

{% block content %}


{% endblock %}

project/users/templates/users/index.html
{% extends 'base.html' %}

{% block content %}
<br>


    <div class="container">
      <div class="panel panel-bubble panel-default outline-blue-border light-blue" >
        <div class="panel-body">
          <h3>New items sold!</h3>
          <p class="lead"> 6 </p>
          <a class="button button-blue" href="{{url_for('orders')}}" role="button">Pick Items Now »</a>
        </div>
      </div>


    <div class="panel panel-bubble panel-default outline-blue-border light-blue" >
      <div class="panel-body">
        <h3>Sales Revenue this week</h3>
        <p class="lead">
          Total: $2,000,000 <br>
          E-bay: $1,000,000 <br>
          Amazon: $1,500,000 <br>
          Other: $500,000
        </p>
        <p class="lead">Total Refunds: $10,000,000</p>
        <a class="button button-blue" href="{{url_for('root')}}"  role="button">View Sales Analytics »</a>
      </div>
    </div>

    <div class="panel panel-bubble panel-default outline-blue-border light-blue" >
      <div class="panel-body">
        <h3>Transactions Details This Week</h3>
        <p class="lead">Total orders: 100</p>
        <a class="button button-blue" href="{{url_for('root')}}" role="button">View Transactions Analytics »</a>
      </div>
    </div>
  </div>

<div class="container">
  <ul>
   {% for user in users %}
    <li>
      {{user.email}},
      {{user.firstname}},
      {{user.lastname}}
    </li>
  {% endfor %}
  </ul>
</div>


{% endblock %}

project/users/templates/users/login.html
{% extends 'base.html' %}

{% block title %}
  Login
{% endblock%}

{% block head %}
  {% if animation == 'login' %}
     <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/login.css') }}">
  {% else %}
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/fadein.css') }}">
  {% endif %}
{% endblock%}


{% block content %}
  <div id="pop-up">
    <div class="container1">
      <h1>Welcome</h1>
      <p>Please login</p>
        <form method="POST" action="{{url_for('users.login')}}">
          {{ form.csrf_token }}
          <p>{{ form.email(placeholder="email") }}
            <br>
              {% if form.email.errors %}
                {% for error in form.email.errors %}
                  {{ error }}
                {% endfor %}
              {% endif %}
          </p>
          <p>
            {{ form.password(placeholder="password") }}
            <br>
              {% if form.password.errors %}
                {% for error in form.password.errors %}
                  {{ error }}
                {% endfor %}
              {% endif %}
          </p>
          <button class="button-black" type="submit">Log In!</button>
          <a href="{{url_for('users.signup')}}" class="button button-black" > Sign Up! </a>
        </form>
    </div>
  </div>

{% endblock %}

project/users/templates/users/show.html
{% extends 'base.html' %}

{% block content %}

<h1>asasd</h1>


{% endblock %}

project/users/templates/users/signup.html
{% extends 'base.html' %}

{% block title %}
  Sign Up
{% endblock%}

{% block head %}
  <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/fadein.css') }}">
{% endblock%}


{% block content %}
  <div id="pop-up">
    <div class="container1">
      <h1>Welcome</h1>
      <p>Please Sign Up!</p>
        <form method="POST" action="{{url_for('users.signup')}}">
            {{ form.csrf_token }}
             <p>{{ form.email(placeholder="email")}}
                <br>
                  {% if form.email.errors %}
                    {% for error in form.email.errors %}
                      {{ error }}
                    {% endfor %}
                  {% endif %}
             </p>
             <p>{{ form.password(placeholder="password") }}
                <br>
                  {% if form.password.errors %}
                    {% for error in form.password.errors %}
                      {{ error }}
                    {% endfor %}
                  {% endif %}
             </p>
             <p>{{ form.firstname(placeholder="first name") }}
                <br>
                  {% if form.firstname.errors %}
                    {% for error in form.firstname.errors %}
                      {{ error }}
                    {% endfor %}
                  {% endif %}
             </p>
             <p>{{ form.lastname(placeholder="last name") }}
                <br>
                  {% if form.lastname.errors %}
                    {% for error in form.lastname.errors %}
                      {{ error }}
                    {% endfor %}
                  {% endif %}
             </p>
            <button type="submit" class="button-black">Sign Up!</button>
          </form>
    </div>
  </div>

{% endblock %}